### ISSUE TITLE
Wrote a silly parser for the ImHex editor

### ISSUE THREAD

**Issue by sethhall** [AbdulRhmanAlfaifi/notepad_parser#1]
Not really a ticket, but I thought you'd like to see this...
https://gist.github.com/sethhall/2365f33aedfc4569f16eea5cdaaf668f

**Comment by AbdulRhmanAlfaifi** [comment]
Hello,
This is good! I only see one issue in you pattern. In the `UnsavedChunk` struct, the checksum should be outside the `if` statement, the `checksum` will always be present in the struct. 
I created a pattern to help me with the parser development but it is kind of ugly, so I didn't add it to the repo :) 
```
#include <type/leb128>
#include <type/time.pat>

using uLEB128 = type::uLEB128;
struct FILETIME_uLEB128 {
    uLEB128 timestamp;
} [[format("format_filetime")]];
struct crc32 {
    u8 hash[4];
} [[format("crc32_format")]];

struct sha256 {
    u8 hash[32];
} [[format("sha256_format")]];


enum CR_TYPE : u8 {
    CRLF       = 0x1,
    CR         = 0x2,
    LF         = 0x3
};

enum encoding : u8 {
    ANSI    = 0x01,
    UTF16LE = 0x02,
    UTF16BE = 0x03,
    UTF8BOM = 0x04,
    UTF8    = 0x05
};

struct np_data {
    char sig[2];
    u8 unkown0;
    bool has_file_path;
    uLEB128 path_size;
       
    if (has_file_path) {
        char16 path[path_size];
        //test(path_size);
        uLEB128 file_size;
        encoding encoding;
        CR_TYPE carriage_return_type;
        FILETIME_uLEB128 last_write_time;
        //to_filetime(this);
        //u8 unkown1;
        sha256 hash;
        u8 unkown2[2];
        uLEB128 cursor_start;
        uLEB128 cursor_end;
        u8 unkown3[6];
    }
    
    uLEB128 file_content_size;
    if (!has_file_path) {
        u8 junk[8];
    }
    char16 file_content[file_content_size];
    bool contain_unsaved_data;
    crc32 checksum;
    

};


fn sha256_format(sha256 bytes) {
    str hash_hex;
    for(u8 i = 0, i < 32, i = i + 1){
        hash_hex = hash_hex + std::format("{:02X}",bytes.hash[i]);
    }
    return hash_hex;
};

fn crc32_format(crc32 bytes) {
    str hash_hex;
    for(u8 i = 0, i < 4, i = i + 1){
        hash_hex = hash_hex + std::format("{:02X}",bytes.hash[i]);
    }
    return hash_hex;
};


fn format_filetime(FILETIME_uLEB128 data){
    u64 tstamp = data.timestamp;
    type::time64_t time64 = data.timestamp;
    std::print("{}", time64);
    return std::format("{}", time64);
};


np_data np_data_at_0x00 @ 0x00;
```
Also, this doesn't have implementation for `UnsavedChunk` & `ConfigBlock` structures.

Will you be able to create a pull request for the pattern?

I would also recommend to add  the functions `sha256_format` & `crc32_format` to retrieve the string representation on the hash. The function `format_filetime` was meant to convert from `uleb128` to actual datetime, but I wasn't able to make it work.

Feel free to change these functions as you see fit, I don't work a lot with `ImHex` pattern, so I am not that familiar with it.

For other people seeing this issue, don't use the pattern I share, use the one shared by @sethhall

**Comment by sethhall** [comment]
Awesome, thanks for the pattern.  I'll integrate improvements from your pattern into mine and make pull request for your repo.

This was the first time I've heard of ImHex editor (so thanks for pointing it out in your blog post!) but I read some of the docs for the pattern language and wrote that.  I also wrote a parser in Spicy which is a language that our team on the Zeek project have been working on for a while. https://github.com/zeek/spicy

Here's the other parser: 
    https://gist.github.com/sethhall/e1dfacc1eb93b0a8dee96b211a8d8428

Its goals are a different than the ImHex pattern language (high performance, streaming parsing) so the language has some different features and works a bit differently generally.  

Anyway, thanks for the blog post!  It was a fun read and a nice, quick little project to implement.

**Comment by AbdulRhmanAlfaifi** [comment]
Thank you,

I have heard of `spicy` before, but never used it. I will try your parser and see, I might use it in future parsers, though it is hard to move from Rust :)

**Comment by sethhall** [comment]
Ok, I addressed all of your feedback and did the pull request.

 - Reduced the hash formatting down to a single function and got rid of the structs.
 - Fixed the timestamp formatting.
 - Fixed issue with checksum not always being parsed (and totally got rid of the if statement)
 - Did some other little cleanup, you can see the diff here... https://gist.github.com/sethhall/2365f33aedfc4569f16eea5cdaaf668f/revisions

**Comment by sethhall** [comment]
I went ahead and filed a merge request for the ImHex pattern repo too so that it can be built in... https://github.com/WerWolv/ImHex-Patterns/pull/297
